spring:
  application:
    name: eureka-server2

server:
  port: 8761

eureka:
  instance:
    # 如果hostname写成localhost会相互发现不了，集群中hostname不能一样
    hostname: eureka-server2
  server:
    # 只能在开发环境关闭
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

